name: 'telecom_cognitive_platform'
version: '1.0'
config-version: 2
profile: 'default'

source-paths: ["models"]
model-paths: ["models"]
seed-paths: ["data"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target"]
